Workstation docs update
stackhpc/azimuth-user-docs pull request #2
Opened 2023-10-09 14:10 UTC by assumptionsandg

Basic EESSI and podman documentation added in this patch.

2023-10-12 09:45 UTC, JohnGarbutt commented on docs/platforms/linux-workstation.md
> +If setting up the webserver didn't produce any unexpected behaviour, podman is running correctly in your Workstation appliance. For more advanced information about using podman, you can check out the
I would be really tempted to add:

* building an example container and run it (buildah?)
* using that container will apptainer and podman

2023-10-12 09:50 UTC, JohnGarbutt commented on docs/platforms/linux-workstation.md
> +If setting up the webserver didn't produce any unexpected behaviour, podman is running correctly in your Workstation appliance. For more advanced information about using podman, you can check out the
lets use this as an example:
https://github.com/jupyter/docker-stacks/blob/main/images/base-notebook/Dockerfile

And show how to build it locally, then run it with both podman and aptainer, and go into a web browser to see it.

2023-11-10 18:04 UTC, m-bull requested changes

2023-11-10 18:04 UTC, m-bull commented on docs/platforms/linux-workstation.md
> +The [EESSI](http://www.eessi.io/docs/) suite of software is included in the Workstation appliance. This suite includes a diverse collection of toolkits and modules for research computing purposes. Mo
```suggestion
The [EESSI](http://www.eessi.io/docs/) suite of software is included in the Workstation appliance. EESSI includes a diverse collection of toolkits and modules for research computing purposes.
```

2023-11-10 18:04 UTC, m-bull commented on docs/platforms/linux-workstation.md
> +To assess whether the EESSI suite is functioning correctly, you can run some of their demo environments avaliable in the EESSI demo [Github](https://github.com/EESSI/eessi-demo/tree/main) repository.
```suggestion
The EESSI demo environments are available in the [EESSI demo Github repository](https://github.com/EESSI/eessi-demo), which can be cloned using the command below:
```

2023-11-10 18:04 UTC, m-bull commented on docs/platforms/linux-workstation.md
> +As an example, we can run the TensorFlow demo environment to ensure the environment is setup correctly. It is first neccessary to source the EESSI bash environment, to do this please run the followin
This whole section reads a bit like we assume the environment might not be setup properly, which it should always be, because we're managing that setup.

Can we reword a bit so that it reads a bit more like "this is how to run the TensorFlow demo"?

2023-11-10 18:04 UTC, m-bull commented on docs/platforms/linux-workstation.md
> +Now you have a functioning environment, you can begin experimenting with the software included in EESSI. Enter the directory of the EESSI-demo repository we cloned earlier, then enter the TensorFlow
Could we switch these instructions to the third-person? i.e. Remove "you" and make it impersonal?

2023-11-10 18:04 UTC, m-bull commented on docs/platforms/linux-workstation.md
> +Podman is a container framework provided in the Workstation appliance for the purpose of installing, managing and developing OCI containers. We **strongly** recommend installing any software you wish
Again, third-person here I think - e.g. remove "we recommend" and replace with "it is recommended".

2023-11-10 18:04 UTC, m-bull commented on docs/platforms/linux-workstation.md
> +The podman is syntatically similar to the Docker CLI. For instance, we can build and deploy a Jupyter notebook as an example using Podman and access our deployment in the web interface:
```suggestion
The podman CLI is syntatically similar to the Docker CLI. For instance, we can build and deploy a Jupyter notebook as an example using Podman and access our deployment in the web interface:
```

2023-11-10 18:04 UTC, m-bull commented on docs/platforms/linux-workstation.md
> +#### Custom Images
I think this probably belongs in a whole new page targeting Azimuth operators rather than end-users.

2023-11-10 18:04 UTC, m-bull commented on docs/platforms/linux-workstation.md
> +Now we have modifed the playbook to install another package, we can use 'Packer' to generate the image. Using Packer requires that you have access to a cloud with a floating IP. Assuming this is the
Link to Packer docs?

2023-12-11 10:31 UTC, assumptionsandg commented on docs/platforms/linux-workstation.md
> +Now you have a functioning environment, you can begin experimenting with the software included in EESSI. Enter the directory of the EESSI-demo repository we cloned earlier, then enter the TensorFlow
Think i've addressed most cases of this, please let me know if you find anymore.

2023-12-11 10:32 UTC, assumptionsandg commented on docs/platforms/linux-workstation.md
> +#### Custom Images
Moved to `https://github.com/stackhpc/azimuth-config/pull/61`

2023-12-12 11:31 UTC, sd109 commented
Would be good to get this merged ASAP as the Azimuth UI currently says "See user docs for information on EESSI" etc. but the docs don't mention any of those things.

2023-12-14 14:53 UTC, JohnGarbutt approved these changes
Yeah, lets get this in as is, we can iterate as needed.

2023-12-14 14:53 UTC, merged